apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-api
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedabbas96/charts.git
    path: go-api
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true