apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-istiod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedabbas96/charts.git
    path: istio/istiod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
  syncPolicy:
    automated:
      selfHeal: true