apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio/istio-gateway
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedabbas96/charts.git
    path: istio/gateway
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true