apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedabbas96/charts.git
    path: mariadb
    targetRevision: HEAD
    helm:
      values: |-
        architecture: standalone
        auth:
          rootPassword: demo123     
        primary:
          persistence:
            enabled: false
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 200m
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true