apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedabbas96/charts.git
    targetRevision: main                                       
    path: mimir-distributed                          
    helm:
      valueFiles:
        - values/values-mimir.yaml                              
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir                                             
  syncPolicy:
    automated:
      prune: true
      selfHeal: true